package view;

public enum Neighbourhood {

	BANISHORA, DIANABAD, SUHATAREKA, KRASNO_SELO, GEO_MILEV, LYULIN, SITNYAKOVO, KRASNA_POLYANA, SERDIKA, LAGERA,
	ZONA_B5, ZONA_B18, DURVENITSA, SLATINA, HRISTO_SMIRNENSKI, SVETA_TROITSA, TOLSTOY, RAZSADNIKA, MODERNO_PREDGRADIE,
	NADEZHDA, ORLANDOVTSI, YUZHEN_PARK,	ZAPADEN_PARK, ILINDEN, BENKOVSKI, MOTOPISTA, OBELYA, KVARTAL_FILIPOVTSI,
	KNYAZHEVO, SIMEONOVO, OVCHAKUPEL, STRELBISHTE, STUDENTSKI_GRAD,	ZAHARNA_FABRIKA, PODUENE, GORNA_BANYA, OBORISHTE,
	DRAGALEVTSI, MLADOST, BYKSTON, HADZHI_DIMITYR, LOZENETS, FAKULTETA, NOVI_ISKYR, DRUZHBA
	
}
