package basic;

public enum Neighbourhood {

	BANISHORA, DIANABAD, SUHATAREKA, KRASNOSELO, GEOMILEV, LYULIN, SITNYAKOVO, KRASNAPOLYANA, SERDIKA, LAGERA,
	ZONAB5, ZONAB18, DURVENITSA, SLATINA, HRISTOSMIRNENSKI, SVETATROITSA, TOLSTOY, RAZSADNIKA, MODERNOPREDGRADIE,
	NADEZHDA, ORLANDOVTSI, YUZHENPARK,	ZAPADENPARK, ILINDEN, BENKOVSKI, MOTOPISTA, OBELYA, KVARTALFILIPOVTSI,
	KNYAZHEVO, SIMEONOVO, OVCHAKUPEL, STRELBISHTE, STUDENTSKIGRAD,	ZAHARNAFABRIKA, PODUENE, GORNABANYA, OBORISHTE,
	DRAGALEVTSI, MLADOST, BYKSTON, HADZHIDIMITYR, LOZENETS, FAKULTETA, NOVIISKYR, DRUZHBA
	
}
