package basic;

public enum MealType {
     SALAD,SOUP,PASTA,PIZZA,ALAMINUT,BBQ,FISH,BREAD,SOUCE,DESERT,DRINKS,VEGETERIAN,OSNOVNO,
     // POD VIDOVE ZA NQKOI OT IASTIATA S VID MESO ILI BBQ
     PORK,CHICKEN,BEEF,DUCK,
     // POD VID ZA PASTA
     SPAGHETTI,LASAGNA,
     // POD VID DRINKS
     BEER,WINE,STRONG_ALCOHOL,NON_ALCOHOL
     
     
     // TODO: MORE TO BE ADDED
    
}
